blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^$', views.list_of_post, name='list_of_post'),
	url(r'^(?P<slug>[-\w]+)/$',views.post_detail, name='post_detail'),
	url(r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_post_by_category, name='list_of_post_by_category'),
	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),
	url(r'^backend/post/new/$', views.new_post, name='new_post'),
	url(r'^backend/post/$', views.list_of_post_backend, name='list_of_post_backend'),
	url(r'^backend/(?P<slug>[-\w]+)/edit/$', views.edit_post, name='edit_post'),
	url(r'^backend/(?P<slug>[-\w]+)/delete/$', views.delete_post, name='delete_post')
]

merafaisla/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^$', views.home, name='home'),
]

blog/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.template.defaultfilters import slugify

# Create your models here.

class Category(models.Model):
	"""docstring for Category"""
	name = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_absolute_url(self):
		return reverse('blog:list_of_post_by_category',args=[self.slug])
			
	def __str__(self):
		return self.name
		

class Post(models.Model):
	"""docstring for Post"""
	STATUS_CHOICES = (
		('draft','Draft'),
		('published','Published'),
	)
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique=True)
	content = models.TextField()
	seo_title = models.CharField(max_length=250)
	seo_description = models.CharField(max_length=160)
	author = models.ForeignKey(User,related_name='blog_posts')
	published = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=9,choices=STATUS_CHOICES,default='draft')


	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('blog:post_detail',args=[self.slug])


	def __str__(self):
		return self.title


class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	user = models.CharField(max_length=250)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	approved = models.BooleanField(default=False)

	def approved(self):
		self.approved = True
		self.save()

	def __str__(self):
		return self.user

blog/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('user','email','body')

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title','author','content','category','seo_title','seo_description','status')

		

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Category, Comment 
from .forms import CommentForm, PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.contrib import messages
# Create your views here.
def list_of_post(request):
	post = Post.objects.filter(status='Published')
	paginator = Paginator(post, 1)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts =paginator.page(paginator.num_pages)
	template = 'blog/post/list_of_post.html'
	#optional
	context = {'posts':posts, 'page':page}
	return render(request, template, context)

def home(request):
	template = 'blog/base.html'
	return render(request, template)

def post_detail(request,slug):
	post = get_object_or_404(Post,slug=slug)
	context = {'post':post}
	if post.status == 'published':
		template = 'blog/post/post_detail.html'
		return render(request,template,context)
	else:
		template = 'blog/post/post_preview.html'
		return render(request,template,context)

def list_of_post_by_category(request,category_slug):
	categories = Category.objects.all()
	post = Post.objects.filter(status='Published')
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		post = Post.objects.filter(category=category)
	template = 'blog/category/list_of_post_by_category.html'
	context = {'categories':categories, 'post':post, 'category':category}
	return render(request,template,context)

def add_comment(request,slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = CommentForm()
	template = 'blog/post/add_comment.html'
	context = {'form':form}
	return render(request,template,context)
	
########################BACKEND#######################################

def new_post(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			#post.author = request.user
			post.save()
			return redirect('blog:post_detail', slug=post.slug)
	else:
		form = PostForm()
	template = 'blog/backend/new_post.html'
	context = { 'form':form}
	return render(request,template,context)

def list_of_post_backend(request):
	post = Post.objects.all()
	paginator = Paginator(post, 2)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts =paginator.page(paginator.num_pages)
	template = 'blog/backend/list_of_post_backend.html'
	#optional
	context = {'posts':posts, 'page':page}
	return render(request, template, context)

def edit_post(request, slug):
	post = get_object_or_404(Post, slug=slug)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			#post.author = request.user
			post.save()
			return redirect('blog:list_of_post_backend')
	else:
		form = PostForm(instance=post)
	template = 'blog/backend/new_post.html'
	context = { 'form':form}
	return render(request, template, context)

def delete_post(request, slug):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	post = get_object_or_404(Post, slug=slug)
	post.delete()
	messages.success(request, "Successfully deleted!")
	return redirect('blog:list_of_post_backend')
	

blog/templates/blog/backend/list_of_post_backend.html
{% extends 'blog/base.html' %}

{% block title %}Backend Post{% endblock %}

{% block content %}
<div class="table-responsive">
<br>
<br>
	<table class="table table-hover">
		<tr>
			<th>Title</th>
			<th>Slug</th>
			<th>Author</th>
			<th>Published</th>
			<th>Status</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		{% for post in posts %}
			{% if post.status == 'draft' %}
				<tr class="danger">
					<td>{{ post.title }}</td>
					<td>{{ post.slug }}</td>
					<td>{{ post.author }}</td>
					<td>{{ post.published }}</td>
					<td>{{ post.status }}</td>
					<td><a href="{% url 'blog:edit_post' slug=post.slug %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true">Edit</span></button></a></td>
					<td><a href="{% url 'blog:delete_post' slug=post.slug %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash" aria-hidden="true">Delete</span></button></a></td>
				</tr>
			{% else %}
				<tr class="success">
					<td>{{ post.title }}</td>
					<td>{{ post.slug }}</td>
					<td>{{ post.author }}</td>
					<td>{{ post.published }}</td>
					<td>{{ post.status }}</td>
					<td><a href="#"><button type="button" class="btn btn-disabled "><span class="glyphicon glyphicon-pencil" aria-hidden="true">Edit</span></button></a></td>
					<td><a href="{% url 'blog:delete_post' slug=post.slug %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash" aria-hidden="true">Delete</span></button></a></td>
				</tr>
			{% endif %}
		{% endfor %}
	</table>
	{% include 'blog/paginator.html' with page=posts %}
</div>

{% endblock %}

blog/templates/blog/backend/new_post.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<h1>New Post :</h1>
	<form method="POST" class="post-form">{% csrf_token%}
		{{ form|crispy }}
	<button type="submit" class="btn btn-success">Save</button>
	</form>
	

{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="">
   
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css'%}">
	<script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js'%}"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="container">
  {% include 'blog/messages.html' %}
	{% block content %}
	{% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
<script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js'%}"></script>

</body>
</html>

blog/templates/blog/category/list_of_post_by_category.html
{% extends 'blog/base.html' %}
{% block description %}This is a categgory : {% endblock %}
{%block title%}{{ category.name }}{%endblock%}

{%block content%}
	<div class="row">
	<div class="col-md-8">
	<div class="page-header">
		<h1>Latest Blog Posts in {{ category.name }}:</h1>
	</div>
	{%for posts in post%}
		<h2><a href="{{ posts.get_absolute_url}}">{{posts.title}}</a></h2>
		<small>Written by : {{posts.author}} on {{posts.published}}</small>
		<hr>
		{{posts.content|truncatewords:40|linebreaks}}
	{%endfor%}
    </div>
    <div class="col-md-4"></div>
    <div class="page-header">
		<h1>Sidebar :</h1>
	</div>
</div>
{%endblock%}

blog/templates/blog/messages.html
{% if messages %}
	{% for message in messages %}
		{% if message.tags %}
		<div class="alert alert-{{ message.tags }}">{{ message }}</div>
		{% endif %}
	{% endfor %}
{% endif %}

blog/templates/blog/paginator.html
<nav aria-label="Page Navigation">
{% if page.has_other_pages %}
	<ul class="pagination">
		{% if page.has_previous %}
			<li><a aria-label="Previous" href="?page={{page.previous_page_number}}">&laquo;</a></li>
		{% else %}
			<li class="disabled"><span>&laquo;</span></li>
		{% endif %}
		{% for pages in page.paginator.page_range%}
			{% if page.number == pages %}
				<li class="active"><span>{{ pages }}<span class="sr-only">(current)</span></span></li>
			{% else %}
				<li><a href="?page={{pages}}">{{pages}}</a></li>
			{% endif %}
		{% endfor %}
		{% if page.has_next %}
			<li><a href="?page={{ page.next_page_number }}">&raquo;</a></li>
		{% else %}
			<li class="disabled"><span>&raquo;</span></li>
		{% endif %}
	</ul>
{% endif %}
</nav>

blog/templates/blog/post/add_comment.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags%}

{% block  content %}
<div class="row">
<div class="col-md-8">
	<div class="page-header"><h1>Add new comment</h1></div>
	<form method="POST"> {% csrf_token %}
		{{ form|crispy }}
		<button type="submit" class="btn btn-success">Submit</button>
	</form></div>
<div class="col-md-4"><div class="page-header"><h1>Sidebar</h1></div></div>
		


{% endblock %}

blog/templates/blog/post/list_of_post.html
{% extends 'blog/base.html' %}
{% block description %}This is description : {% endblock %}
{%block title%}List of blog posts :{%endblock%}

{%block content%}
	<div class="row">
	<div class="col-md-8">
	<div class="page-header">
		<h1>Latest Blog Posts :</h1>
	</div>
	{% for post in posts %}
		<h2><a href="{{ post.get_absolute_url}}">{{post.title}}</a></h2>
		<small>Written by : {{post.author}} on {{post.published}} in <a href="{{ post.category.get_absolute_url}}">{{post.category}}</a></small>
		<hr>
		{{post.content|truncatewords:40|linebreaks}}
	{% endfor %}
	{% include 'blog/paginator.html' with page=posts %}
    </div>
    <div class="col-md-4"></div>
    <div class="page-header">
		<h1>Sidebar :</h1>
	</div>
</div>
{%endblock%}

blog/templates/blog/post/post_detail.html
{% extends 'blog/base.html' %}

{%block description%}{{post.seo_description}}{%endblock%}

{%block title%}{{post.seo_title}}{%endblock%}

{%block content%}
<div  class="row>">
	<div class="col-md-8">
	<div class="page-header">
		<h1>{{post.title}}</h1>
	</div>
		<small>Written by : {{post.author}} on {{post.published}} in <a href="{{ posts.category.get_absolute_url}}">{{post.category}}</a></small>
		<hr>
		{{post.content|linebreaks}}
		<div class="page-header">
		<h1>Comments<small> Number of comments : {{ post.comments.count }}</small></h1>
	</div>
		
		<p class="text-center"><button type="button" class="btn btn-defualt"><a href="{% url 'blog:add_comment' slug=post.slug %}">Leave a comment</a></button></p>		
		{% for comment in post.comments.all%}
		<div class="panel panel-default">
		<div class="panel-heading"> By {{ comment.user }} on {{ comment.created }} </div>
		<div class="panel-body">{{ comment.body }}</div>
			</div>
		{%empty%}
			<p>There is no comments!</p>	
		{% endfor %}
	</div>
</div>
{%endblock%}

blog/templates/blog/post/post_preview.html
{% extends 'blog/base.html' %}

{%block description%}{{post.seo_description}}{%endblock%}

{%block title%}{{post.seo_title}}{%endblock%}

{%block content%}
<div  class="row>">
	<div class="col-md-8">
	<div class="alert alert-danger" role="alert">This is a post preview</div>
	<div class="page-header">
		<h1>{{post.title}}</h1>
	</div>
		<small>Written by : {{post.author}} on {{post.published}} in <a href="{{ posts.category.get_absolute_url}}">{{post.category}}</a></small>
		<hr>
		{{post.content|linebreaks}}
		<div class="page-header">
		<h1>Comments<small> Number of comments : {{ post.comments.count }}</small></h1>
	</div>
		
		<p class="text-center"><button type="button" class="btn btn-defualt"><a href="{% url 'blog:add_comment' slug=post.slug %}">Leave a comment</a></button></p>		
		{% for comment in post.comments.all%}
		<div class="panel panel-default">
		<div class="panel-heading"> By {{ comment.user }} on {{ comment.created }} </div>
		<div class="panel-body">{{ comment.body }}</div>
			</div>
		{%empty%}
			<p>There is no comments!</p>	
		{% endfor %}
	</div>
</div>
{%endblock%}